# Generated by Selenium IDE

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestTest():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test(self):
        self.open_home_page()
        self.login()
        self.open_group_page()
        self.create_group()
        self.logout()

    def open_home_page(self):
        self.driver.get("http://localhost/addressbook/")
        self.driver.set_window_size(1050, 708)

    def login(self):
        self.driver.find_element(By.NAME, "user").send_keys("admin")
        self.driver.find_element(By.NAME, "pass").send_keys("secret")
        self.driver.find_element(By.NAME, "pass").send_keys(Keys.ENTER)

    def open_group_page(self):
        self.driver.find_element(By.LINK_TEXT, "groups").click()

    def create_group(self):
        self.driver.find_element(By.NAME, "new").click()
        self.driver.find_element(By.NAME, "group_name").click()
        self.driver.find_element(By.NAME, "group_name").send_keys("test-1")
        self.driver.find_element(By.NAME, "group_header").send_keys("1")
        self.driver.find_element(By.NAME, "group_footer").click()
        self.driver.find_element(By.NAME, "group_footer").send_keys("2")
        self.driver.find_element(By.NAME, "submit").click()

    def logout(self):
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
